### ISSUE TITLE
Large TAGS file

### ISSUE THREAD

**Issue by prama01720** [chriswheeldon/vscode-ctags#1]
Hi

I had difficulty in using a fairly large tag file - my tag file size is 504M and it would not load properly - from Linux Kernel Source Browsing

**Comment by chriswheeldon** [comment]
Thanks, @prama01720. I'll take a look at this.

**Comment by chriswheeldon** [comment]
@prama01720 this issue should be fixed in the next release.

**Comment by prama01720** [comment]
Thank you. In case you need me to test anything please let me know. I am willing to help.
Regards
Rama

    On Wednesday, November 14, 2018, 1:09:27 PM EST, Chris Wheeldon <notifications@github.com> wrote:  
 
 
@prama01720 this issue should be fixed in the next release.

**Comment by chriswheeldon** [comment]
> Thank you. In case you need me to test anything please let me know. I am willing to help. Regards 

@prama01720 , please give version 0.0.7 (the latest published version) a try and see if that now works for you. Thanks.
